"""added new constraint

Revision ID: 1cea6d78be53
Revises: 2b3d5294ed1b
Create Date: 2023-11-11 21:43:22.749724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cea6d78be53'
down_revision: Union[str, None] = '2b3d5294ed1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('product_description_product_id_fkey', 'product_description', type_='foreignkey')
    op.create_foreign_key(None, 'product_description', 'product', ['product_id'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product_description', type_='foreignkey')
    op.create_foreign_key('product_description_product_id_fkey', 'product_description', 'product', ['product_id'], ['id'])
    # ### end Alembic commands ###
