"""empty message

Revision ID: 521172b25b1d
Revises: c75f0f9a455a
Create Date: 2023-12-05 02:16:08.957638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '521172b25b1d'
down_revision: Union[str, None] = 'c75f0f9a455a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_requests', sa.Column('passport_series', sa.String(length=4), nullable=True))
    op.add_column('order_requests', sa.Column('passport_number', sa.String(length=30), nullable=True))
    op.add_column('order_requests', sa.Column('passport_date_of_issue', sa.Date(), nullable=True))
    op.add_column('order_requests', sa.Column('passport_organization', sa.String(length=255), nullable=True))
    op.add_column('order_requests', sa.Column('tin', sa.String(length=12), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_requests', 'tin')
    op.drop_column('order_requests', 'passport_organization')
    op.drop_column('order_requests', 'passport_date_of_issue')
    op.drop_column('order_requests', 'passport_number')
    op.drop_column('order_requests', 'passport_series')
    # ### end Alembic commands ###
