"""added order request

Revision ID: 5452dcbef172
Revises: 0f88e8dd620e
Create Date: 2023-11-15 04:22:57.390102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5452dcbef172'
down_revision: Union[str, None] = '0f88e8dd620e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name_of_recipient', sa.String(length=150), nullable=False),
    sa.Column('phone_of_recipient', sa.String(length=150), nullable=False),
    sa.Column('additional_num', sa.String(length=150), nullable=False),
    sa.Column('address_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['address.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_requests')
    # ### end Alembic commands ###
