"""14 name column

Revision ID: 6268a8088a74
Revises: 23ab83e014f1
Create Date: 2023-10-24 22:12:33.313347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6268a8088a74'
down_revision: Union[str, None] = '23ab83e014f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review_blog', sa.Column('name_of_user', sa.String(length=150), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('review_blog', 'name_of_user')
    # ### end Alembic commands ###
