"""updating user

Revision ID: b4a2ca28cbd6
Revises: e4813c6cf391
Create Date: 2023-12-05 13:58:08.989047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4a2ca28cbd6'
down_revision: Union[str, None] = 'e4813c6cf391'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('review_blog_user_id_fkey', 'review_blog', type_='foreignkey')
    op.create_foreign_key(None, 'review_blog', 'user', ['user_id'], ['id'], ondelete='cascade')
    op.add_column('user', sa.Column('created_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'created_date')
    op.drop_constraint(None, 'review_blog', type_='foreignkey')
    op.create_foreign_key('review_blog_user_id_fkey', 'review_blog', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
