"""adjusted sdek table

Revision ID: c318a71034c2
Revises: 36e55317970e
Create Date: 2023-11-15 05:59:17.276895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c318a71034c2'
down_revision: Union[str, None] = '36e55317970e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('product_for_order_order_request_id_fkey', 'product_for_order', type_='foreignkey')
    op.create_foreign_key(None, 'product_for_order', 'order_requests', ['order_request_id'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product_for_order', type_='foreignkey')
    op.create_foreign_key('product_for_order_order_request_id_fkey', 'product_for_order', 'order_requests', ['order_request_id'], ['id'])
    # ### end Alembic commands ###
