"""added parent_category

Revision ID: c75f0f9a455a
Revises: c5d442416435
Create Date: 2023-11-17 19:44:46.818571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c75f0f9a455a'
down_revision: Union[str, None] = 'c5d442416435'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parent_category',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('category', sa.Column('parent_category_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'category', 'parent_category', ['parent_category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'category', type_='foreignkey')
    op.drop_column('category', 'parent_category_id')
    op.drop_table('parent_category')
    # ### end Alembic commands ###
