"""added new columns to product

Revision ID: d24f5d3c7848
Revises: f61c1990e09c
Create Date: 2023-12-08 18:34:41.449846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd24f5d3c7848'
down_revision: Union[str, None] = 'f61c1990e09c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('length', sa.Integer(), nullable=False))
    op.add_column('product', sa.Column('width', sa.Integer(), nullable=False))
    op.add_column('product', sa.Column('height', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'height')
    op.drop_column('product', 'width')
    op.drop_column('product', 'length')
    # ### end Alembic commands ###
