"""updating datetime

Revision ID: e4813c6cf391
Revises: 18e6c6787af6
Create Date: 2023-12-05 13:45:09.527697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4813c6cf391'
down_revision: Union[str, None] = '18e6c6787af6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_requests', sa.Column('created_at', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_requests', 'created_at')
    # ### end Alembic commands ###
