"""added product for order

Revision ID: ed2f5c5965cb
Revises: 5452dcbef172
Create Date: 2023-11-15 04:33:39.137162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed2f5c5965cb'
down_revision: Union[str, None] = '5452dcbef172'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_for_order',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_request_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_request_id'], ['order_requests.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('order_requests', sa.Column('order_weigth', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_requests', 'order_weigth')
    op.drop_table('product_for_order')
    # ### end Alembic commands ###
